/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
        "on-primary-container": "#f5fff7",
        "tertiary-container": "#b95650",
        "background": "#f8f9f9",
        "primary-container": "#00855e",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c2c6d3",
        "inverse-primary": "#69dbab",
        "tertiary-fixed": "#ffdad6",
        "surface-variant": "#e1e3e3",
        "on-secondary-container": "#5e636e",
        "on-primary-fixed-variant": "#005138",
        "on-primary-fixed": "#002114",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f8f9f9",
        "surface-container-highest": "#e1e3e3",
        "on-tertiary-container": "#fffbff",
        "primary": "#006949",
        "on-background": "#191c1c",
        "on-secondary-fixed-variant": "#424751",
        "on-surface-variant": "#3d4a43",
        "primary-fixed-dim": "#69dbab",
        "on-error": "#ffffff",
        "surface-tint": "#006c4b",
        "inverse-on-surface": "#f0f1f1",
        "surface-container-low": "#f3f4f4",
        "on-secondary": "#ffffff",
        "tertiary": "#9a3e39",
        "secondary-fixed": "#dee2ef",
        "on-error-container": "#93000a",
        "primary-fixed": "#86f8c5",
        "error": "#ba1a1a",
        "on-tertiary-fixed": "#410003",
        "secondary": "#595e69",
        "outline-variant": "#bccac0",
        "on-tertiary-fixed-variant": "#7e2a26",
        "surface-container": "#edeeee",
        "surface-dim": "#d9dada",
        "inverse-surface": "#2e3131",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#ffb3ad",
        "secondary-container": "#dbdfec",
        "on-secondary-fixed": "#171c25",
        "surface": "#f8f9f9",
        "on-surface": "#191c1c",
        "surface-container-high": "#e7e8e8",
        "outline": "#6d7a72"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "container-padding": "24px",
        "gutter-table": "12px",
        "density-comfortable": "16px",
        "density-compact": "8px",
        "margin-section": "32px",
        "unit": "4px"
      },
      "fontFamily": {
        "financial-data": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-sm": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Geist", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      "fontSize": {
        "financial-data": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
