/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthLaporanRouteImport } from './routes/_auth.laporan'
import { Route as AuthMahasiswaRouteImport } from './routes/_auth.mahasiswa'
import { Route as AuthMasterBiayaRouteImport } from './routes/_auth.master-biaya'
import { Route as AuthPembayaranRouteImport } from './routes/_auth.pembayaran'
import { Route as AuthTagihanRouteImport } from './routes/_auth.tagihan'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentRiwayatRouteImport } from './routes/student.riwayat'
import { Route as StudentTagihanRouteImport } from './routes/student.tagihan'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLaporanRoute = AuthLaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMahasiswaRoute = AuthMahasiswaRouteImport.update({
  id: '/mahasiswa',
  path: '/mahasiswa',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMasterBiayaRoute = AuthMasterBiayaRouteImport.update({
  id: '/master-biaya',
  path: '/master-biaya',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPembayaranRoute = AuthPembayaranRouteImport.update({
  id: '/pembayaran',
  path: '/pembayaran',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTagihanRoute = AuthTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => AuthRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentRiwayatRoute = StudentRiwayatRouteImport.update({
  id: '/riwayat',
  path: '/riwayat',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTagihanRoute = StudentTagihanRouteImport.update({
  id: '/tagihan',
  path: '/tagihan',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/student': typeof StudentRouteWithChildren
  '/laporan': typeof AuthLaporanRoute
  '/mahasiswa': typeof AuthMahasiswaRoute
  '/master-biaya': typeof AuthMasterBiayaRoute
  '/pembayaran': typeof AuthPembayaranRoute
  '/tagihan': typeof AuthTagihanRoute
  '/student/riwayat': typeof StudentRiwayatRoute
  '/student/tagihan': typeof StudentTagihanRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/laporan': typeof AuthLaporanRoute
  '/mahasiswa': typeof AuthMahasiswaRoute
  '/master-biaya': typeof AuthMasterBiayaRoute
  '/pembayaran': typeof AuthPembayaranRoute
  '/tagihan': typeof AuthTagihanRoute
  '/student/riwayat': typeof StudentRiwayatRoute
  '/student/tagihan': typeof StudentTagihanRoute
  '/': typeof AuthIndexRoute
  '/student': typeof StudentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRoute
  '/student': typeof StudentRouteWithChildren
  '/_auth/laporan': typeof AuthLaporanRoute
  '/_auth/mahasiswa': typeof AuthMahasiswaRoute
  '/_auth/master-biaya': typeof AuthMasterBiayaRoute
  '/_auth/pembayaran': typeof AuthPembayaranRoute
  '/_auth/tagihan': typeof AuthTagihanRoute
  '/student/riwayat': typeof StudentRiwayatRoute
  '/student/tagihan': typeof StudentTagihanRoute
  '/_auth/': typeof AuthIndexRoute
  '/student/': typeof StudentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/portal'
    | '/student'
    | '/laporan'
    | '/mahasiswa'
    | '/master-biaya'
    | '/pembayaran'
    | '/tagihan'
    | '/student/riwayat'
    | '/student/tagihan'
    | '/student/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/portal'
    | '/laporan'
    | '/mahasiswa'
    | '/master-biaya'
    | '/pembayaran'
    | '/tagihan'
    | '/student/riwayat'
    | '/student/tagihan'
    | '/'
    | '/student'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/portal'
    | '/student'
    | '/_auth/laporan'
    | '/_auth/mahasiswa'
    | '/_auth/master-biaya'
    | '/_auth/pembayaran'
    | '/_auth/tagihan'
    | '/student/riwayat'
    | '/student/tagihan'
    | '/_auth/'
    | '/student/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRoute
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/laporan': {
      id: '/_auth/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof AuthLaporanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/mahasiswa': {
      id: '/_auth/mahasiswa'
      path: '/mahasiswa'
      fullPath: '/mahasiswa'
      preLoaderRoute: typeof AuthMahasiswaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/master-biaya': {
      id: '/_auth/master-biaya'
      path: '/master-biaya'
      fullPath: '/master-biaya'
      preLoaderRoute: typeof AuthMasterBiayaRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/pembayaran': {
      id: '/_auth/pembayaran'
      path: '/pembayaran'
      fullPath: '/pembayaran'
      preLoaderRoute: typeof AuthPembayaranRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tagihan': {
      id: '/_auth/tagihan'
      path: '/tagihan'
      fullPath: '/tagihan'
      preLoaderRoute: typeof AuthTagihanRouteImport
      parentRoute: typeof AuthRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/riwayat': {
      id: '/student/riwayat'
      path: '/riwayat'
      fullPath: '/student/riwayat'
      preLoaderRoute: typeof StudentRiwayatRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tagihan': {
      id: '/student/tagihan'
      path: '/tagihan'
      fullPath: '/student/tagihan'
      preLoaderRoute: typeof StudentTagihanRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLaporanRoute: typeof AuthLaporanRoute
  AuthMahasiswaRoute: typeof AuthMahasiswaRoute
  AuthMasterBiayaRoute: typeof AuthMasterBiayaRoute
  AuthPembayaranRoute: typeof AuthPembayaranRoute
  AuthTagihanRoute: typeof AuthTagihanRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLaporanRoute: AuthLaporanRoute,
  AuthMahasiswaRoute: AuthMahasiswaRoute,
  AuthMasterBiayaRoute: AuthMasterBiayaRoute,
  AuthPembayaranRoute: AuthPembayaranRoute,
  AuthTagihanRoute: AuthTagihanRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface StudentRouteChildren {
  StudentRiwayatRoute: typeof StudentRiwayatRoute
  StudentTagihanRoute: typeof StudentTagihanRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentRiwayatRoute: StudentRiwayatRoute,
  StudentTagihanRoute: StudentTagihanRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRoute,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
